### ISSUE TITLE
get_link  will always return absolute urls instead of relative urls, making it hard to author content/test out locally

### ISSUE THREAD

**Issue by silkentrance** [django-cms/djangocms-link#200]
To follow up on #165

I tend to believe that the placeholder cms_page is redundant as Site.objects.get_current() will already return the correct site. And, considering that any placeholder.page.site is always the current site, when available, the code could be reduced to just

```
    def get_link(self):
        if self.internal_link:
            ref_page = self.internal_link
            link = ref_page.get_absolute_url()
            ref_page_site_id = ref_page.node.site_id
            if ref_page_site_id != Site.objects.get_current().pk:
                ref_site = Site.objects._get_site_by_id(ref_page_site_id).domain
                link = '//{}{}'.format(ref_site, link)

  ...
```

I have implemented this locally and it works like a charm, unless I missed some very specific detail :smile: 

I can provide you with a PR for this if you want.

**Comment by marksweb** [comment]
@silkentrance Yes, I'd agree that going through the placeholder to get a site_id in order to find the correct Site object isn't the best way to go about things.

However I don't think you can simplify `ref_page_site_id` like that. The `node` attr needs checking as it is now.

**Comment by silkentrance** [comment]
I have played around with links in static placeholders, links in modules, links linking to pages from a different site than the current one. As of now, everything seems to be working just fine.
