### ISSUE TITLE
django-treebeard requirement

### ISSUE THREAD

**Issue by petrklus** [django-cms/djangocms-link#209]
Hi,

I have noticed that the version 3.1.0 introduced the following line:

https://github.com/django-cms/djangocms-link/blob/f1b51a9ec2a706a3d52eb04bc6dac1796242b946/setup.py#L11

Is this really required? I recall there were issues with some versions of treebeard but, for example, 4.5.1 seems no longer have the issues.

**Comment by marksweb** [comment]
@petrklus you're right. That shouldn't be there imo. Treebeard is a requirement of the cms itself & to list it in packages like this only adds to the complexity of dependency management.

**Comment by petrklus** [comment]
Seems to have been added here https://github.com/django-cms/djangocms-link/commit/2e934cf4bb3d114ebf66ec70b12502f459e4f328

**Comment by calbear47** [comment]
I see this was merged to master. Can we cut a new release with this update?

**Comment by fsbraun** [comment]
@calbear47  Version 3.1.1 is released which includes @petrklus's fix.
